import React, { Component } from 'react';
import ReactWordcloud from 'react-wordcloud';
import { Button, Icon, Image, Label, Modal } from 'semantic-ui-react';

import './LabelCloud.css'; 

import { 
  withFirebase 
} from '../Firebase';

class LabelCloudBase extends Component {
  constructor(props) {
    super(props);
    this.state = { 
      modalOpen: false,
      currentUser: '',
      currentLabel: '',
      labelUnforgettableness: null,
      databaseLabels: null,
      searchResponse: null
    };
    this.handleGenerateData = this.handleGenerateData.bind(this);
    this.handleMarkAsUnforgettable = this.handleMarkAsUnforgettable.bind(this);
  }

  componentDidMount() {
    // Retrieves the search data already generated by other users for the labels
    this.props.firebase.labels().on('value', snapshot => {
      const labelObject = snapshot.val();

      if (labelObject) {
        this.setState({
          databaseLabels: labelObject
        })
      }
    });

    var userId = this.props.firebase.auth.currentUser.uid;
    this.setState({ currentUser: userId });

    // Get whether the labels are unforgettable or not
    this.props.firebase.users().on('value', snapshot => {
      const labelUnforgettableness = snapshot.exportVal()[userId].label_unforgettableness;
      
      this.setState({
        labelUnforgettableness: labelUnforgettableness
      });  
    });
  }

  componentWillUnmount() {
    this.props.firebase.labels().off();
    this.props.firebase.users().off();
  }

  handleOpen = () => this.setState({ modalOpen: true })
  handleClose = () => this.setState({ modalOpen: false })

  handleGenerateData = (e) => {
    e.preventDefault();
    this.setState({ searchResultsLoading: true });

    const { databaseLabels, currentLabel } = this.state;

    const labelValue = currentLabel.text;

    if (databaseLabels[labelValue]) {
      console.log('Label search results already found in database', databaseLabels[labelValue]);
      this.setState({ searchResultsLoading: false });
      return
    }

    const proxyurl = 'https://cors-anywhere.herokuapp.com/';
    const url = `https://us-central1-unforgettable-30030.cloudfunctions.net/getGoogleSearchResults?label=${encodeURIComponent(labelValue)}`

    fetch(proxyurl + url, {
      method: 'POST'
    })
    .then(contents => {
      this.setState({ 
        searchResponse: contents,
        searchResultsLoading: false 
      });
      console.log('Data fetched from Google Search results API', contents);
    })
    .catch(error => {
      console.error('Oops!', error)
      this.setState({ searchResultsLoading: false });
    });
  }

  handleMarkAsUnforgettable = (e) => {
    e.preventDefault();
    this.setState({ markAsUnforgettableLoading: true });

    const { currentLabel, labelUnforgettableness, currentUser } = this.state;

    const labelName = currentLabel.text;
    const markAsUnforgettableRef = this.props.firebase.markAsUnforgettableLabels();

    var markAs;
    if (labelUnforgettableness && labelUnforgettableness[labelName] && labelUnforgettableness[labelName].unforgettableness) {
      switch(labelUnforgettableness[labelName].unforgettableness) {
        case 'UNFORGETTABLE':
          markAs = 'NOT_UNFORGETTABLE';
          break;
        default:
          markAs = 'UNFORGETTABLE';
      }
    } else {
      markAs = 'UNFORGETTABLE';
    }

    // Submit the label to be marked as unforgettable
    markAsUnforgettableRef.push({
      label: labelName,
      user_id: currentUser,
      mark_as: markAs,
      updated_on: new Date().getTime()
    });

    this.setState({ markAsUnforgettableLoading: false });    
  }

  render() {
    const { 
      currentLabel, 
      databaseLabels, 
      labelUnforgettableness, 
      markAsUnforgettableLoading, 
      searchResultsLoading 
    } = this.state;

    const labelValue = currentLabel.text;
    const labelCount = currentLabel.value;

    let labelSearchResults;
    if (labelValue && databaseLabels && databaseLabels[labelValue]) {
      labelSearchResults = databaseLabels[labelValue].searchResults;
    }

    return (
      <>
        <div style={{ margin: '0 auto', maxWidth: '650px' }}>
          <ReactWordcloud
            options={labelCloudOptions}
            words={this.props.data}
            callbacks={{
              onWordClick: (label) => {
                this.setState({
                  modalOpen: true,
                  currentLabel: label
                })
              }
            }}
          />
        </div>
        <Modal
          open={this.state.modalOpen}
          onClose={this.handleClose}
          size='small'
          dimmer={'blurring'}
          closeIcon
        >
          <Modal.Header>
            <h2>Details about the tag '{labelValue}'</h2>
            {markAsUnforgettableLoading ? (
              <Button as='div' labelPosition='right' size='huge'>
                <Button 
                  loading
                  color='red' 
                  size='huge' 
                  onClick={(e) => this.handleMarkAsUnforgettable(e)}>
                  <Icon loading name='heart outline' />
                </Button>
                <Label basic color='red' pointing='left'>
                  Mark as unforgettable
                </Label>
              </Button>
            ) : (
              <Button as='div' labelPosition='right' size='huge'>
                <Button 
                  color='red' 
                  size='huge' 
                  onClick={(e) => this.handleMarkAsUnforgettable(e)}>
                  {labelUnforgettableness && labelUnforgettableness[labelValue] && labelUnforgettableness[labelValue].unforgettableness === 'UNFORGETTABLE' ? (
                    <Icon name='heart' />
                  ) : (
                    <Icon name='heart outline' />
                  )}
                </Button>
                <Label basic color='red' pointing='left'>
                {labelUnforgettableness && labelUnforgettableness[labelValue] && labelUnforgettableness[labelValue].unforgettableness === 'UNFORGETTABLE' ? (
                  'Unmark as unforgettable'
                ) : (
                  'Mark as unforgettable'
                )}
                </Label>
              </Button>
            )}
          </Modal.Header>
            <Modal.Content>
              {labelCount && (
              <p>
                <b>Number of occurrences in your moments</b> {labelCount.toLocaleString(navigator.language, { minimumFractionDigits: 0 })}
              </p>
              )}
              {labelSearchResults && (
                <>
                  <p>
                    <b>Number of search results for the tag</b> {labelSearchResults.search_information.total_results.toLocaleString(navigator.language, { minimumFractionDigits: 0 })}
                  </p>
                  <p>
                    <b>Related searches on the web:</b>
                  </p>
                  <ul>
                    {labelSearchResults.related_searches.map((searchTerm, index) => 
                      <li key={index}><a href={searchTerm.link} rel='noopener noreferrer' target='_blank'>{searchTerm.query}</a></li>)}
                  </ul>
                  {labelSearchResults.knowledge_graph && labelSearchResults.knowledge_graph.images && (
                    <>
                    <p>
                      <b>Related images on the web:</b>
                    </p>
                    <Image.Group size='small'>
                      {labelSearchResults.knowledge_graph.images.map((image, index) => 
                        <Image rounded key={index} src={image}/>
                      )}
                    </Image.Group>
                    </>
                  )}
                  {labelSearchResults.top_stories && (
                    <>
                    <p>
                      <b>Related stories on the web:</b>
                    </p>
                    <ul>
                      {labelSearchResults.top_stories.map((story, index) => 
                        <li key={index}><a href={story.link} rel='noopener noreferrer' target='_blank'>{story.title}</a> (source: {story.source})</li>
                      )}
                    </ul>
                    </>
                  )}
                </>
              )}
              {searchResultsLoading ? (
                <Button searchResultsLoading disabled primary size='huge'>Generate search result data</Button>
              ) : (!labelSearchResults &&
                <Button primary size='huge' onClick={(e) => this.handleGenerateData(e)}>Generate search result data</Button>
              )}
            </Modal.Content>
        </Modal>
      </>
    );
  }
}

const labelCloudOptions = {
  deterministic: true,
  fontFamily: 'Walter Turncoat',
  fontSizes: [10, 36],
  rotations: 1,
  rotationAngles: [0, 90],
  transitionDuration: 1000
};

const LabelCloud = withFirebase(LabelCloudBase);

export default LabelCloud;